CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username CHAR(200) NOT NULL UNIQUE,
  password CHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE device (
  id INT AUTO_INCREMENT PRIMARY KEY,
  password CHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE device_temp_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  device_id INT NOT NULL,
  temp INT NOT NULL,
  at INT UNSIGNED NOT NULL, -- เก็บเวลาเป็นวินาที (epoch)
  FOREIGN KEY (device_id) REFERENCES device(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE my_device (
  id INT AUTO_INCREMENT PRIMARY KEY,
  device_id INT NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (device_id) REFERENCES device(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (user_id) REFERENCES user(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;